services:
  mysql:
    image: 'mysql:8.4.0'
    environment:
      - 'MYSQL_DATABASE=caju'
      - 'MYSQL_PASSWORD=caju'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=caju'
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    network_mode: bridge
